version: "3.9"

services:
  server:
    build:
        context: ./server
        target: dev
        dockerfile: ./Dockerfile
    # depends_on: 
    #   - postgres
    volumes: 
      - ./server:/server 
    env_file:
      - ./server/.env.local
    ports:
      - 8080:8080
    
#   postgres:
#     image: postgres:13-alpine
#     environment:
#       - POSTGRES_DB=my-service
#       - POSTGRES_PASSWORD=my-service
#       - POSTGRES_USER=my-service
#     ports:
#       - 5432:5432
#     volumes:
# #      - db_data:/var/lib/postgresql/data:rw
#       # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       - ./data/db:/var/lib/postgresql/data:rw
    